In [2]:
import torch

In [1]:
def _combine(xs_b, ys_b):
        """Interleaves the x's and the y's into a single sequence."""
        bsize, points, dim = xs_b.shape
        ys_b_wide = torch.cat(
            (
                ys_b.view(bsize, points, 1),
                torch.zeros(bsize, points, dim - 1, device=ys_b.device),
            ),
            axis=2,
        )
        zs = torch.stack((xs_b, ys_b_wide), dim=2)
        zs = zs.view(bsize, 2 * points, dim)
        return zs

In [4]:
x = torch.tensor([[[1,2,3], [10,11,12]]])
y = torch.tensor([[7,8]])
print(_combine(x,y))

tensor([[[ 1.,  2.,  3.],
         [ 7.,  0.,  0.],
         [10., 11., 12.],
         [ 8.,  0.,  0.]]])


In [5]:
b_size = 2
n_dims = 10
n_points = 20
scale = 1
xs_b = torch.randn(b_size, n_points, n_dims)
w_b = torch.randn(b_size, n_dims, 1)
ys_b = scale * (xs_b @ w_b)[:, :, 0]
# print(xs_b)
# print(w_b)
ys_b

tensor([[[-1.4689e+00, -1.4558e+00, -1.5081e+00,  1.1769e+00, -1.1598e+00,
           1.8265e+00, -6.9145e-01, -5.4280e-01,  4.0354e-01,  1.2309e+00],
         [-1.7463e+00, -1.0693e+00, -3.1408e-01,  1.1965e-01, -9.6059e-01,
           7.9196e-01,  1.0076e+00, -8.7727e-01,  2.4256e-01, -9.3299e-01],
         [ 1.0807e+00,  1.1067e+00, -1.5830e+00, -4.2677e-01, -2.9924e-01,
          -1.1659e+00,  2.6834e+00, -9.1328e-01, -1.3140e+00,  6.6616e-01],
         [-3.2126e-01,  5.9178e-01,  1.2041e+00,  1.4624e+00,  7.5387e-01,
           7.5990e-01,  8.0244e-01,  1.1277e-01,  8.8375e-01, -9.7250e-01],
         [-8.9011e-01, -1.4403e+00,  6.1770e-01, -5.6301e-01, -8.4104e-01,
           1.5146e-01,  6.4873e-01, -2.5902e+00,  7.5545e-01,  1.4187e+00],
         [ 1.0330e+00, -1.0538e+00,  1.2007e+00,  3.1371e-01,  7.1217e-01,
          -9.0369e-01, -1.5118e-01, -4.0988e-01, -1.3816e+00,  2.4723e-01],
         [-3.0766e-01, -7.2943e-01,  1.4589e+00, -4.9370e-01, -2.0447e+00,
          -7.9128e-

tensor([[ 2.2281,  4.6466,  1.1819, -1.2489, -0.6356, -3.6995,  2.1925, -0.1880,
         -1.3189,  1.5469, -0.9708, -1.1131,  2.5894, -2.9491,  4.1077,  3.8827,
         -5.2825, -0.7622,  1.7770, -3.6091],
        [ 1.0426,  1.6346, -0.8084, -0.4794,  3.8297, -2.5633,  3.0650,  3.0738,
         -2.1569,  3.4529,  0.9650,  6.3075, -4.4747,  5.0776,  3.5489, -2.5679,
         -1.7057,  0.6496, -0.7636, -3.6518]])