In [2]:
import torch
import pandas as pd
import numpy as np

In [7]:
loaded_grography = torch.load('type_tensor/mlp_31_geography.pt')
loaded_history = torch.load('type_tensor/mlp_31_history.pt')
loaded_literature = torch.load('type_tensor/mlp_31_literature.pt')
loaded_music = torch.load('type_tensor/mlp_31_music.pt')
loaded_science = torch.load('type_tensor/mlp_31_science.pt')
loaded_sport = torch.load('type_tensor/mlp_31_sport.pt')

In [8]:
loaded_grography = loaded_grography[:, -1, :]
loaded_literature = loaded_literature[:, -1, :]
loaded_history = loaded_history[:, -1, :]
loaded_music = loaded_music[:, -1, :]
loaded_science = loaded_science[:, -1, :]
loaded_sport = loaded_sport[:, -1, :]

In [9]:
loaded_sport.shape

torch.Size([30, 4096])

In [31]:
data_group = {"geography":loaded_grography,
              "literature":loaded_literature, 
              "history":loaded_history, 
              "music":loaded_music, 
              "science":loaded_science, 
              "sport":loaded_sport}

In [51]:
def data_cal(loaded_tensor):
    mean_tensor = torch.mean(loaded_tensor, dim=0)
    variance_tensor = torch.var(loaded_tensor, dim=0)
    return {"mean_tensor": mean_tensor, "variance_tensor":variance_tensor}

In [52]:
data_mean_var = {}
for key, value in data_group.items(): 
    data_mean_var[key] = data_cal(value)

In [67]:
print("Number of entries that has a low variance:")
for key in data_mean_var.keys():
    print('  '+key, end=': ')
    threshold = 0.004
    less_than_threshold = data_mean_var[key]["variance_tensor"] <= threshold
    count = less_than_threshold.sum().item()  # use .item() to get the number as a standard Python number
    print(count)

Number of entries that has a low variance:
  geography: 449
  literature: 259
  history: 168
  music: 33
  science: 96
  sport: 215


tensor([0.0096, 0.0082, 0.0519,  ..., 0.0261, 0.0089, 0.0436], device='cuda:0',
       dtype=torch.float16)
tensor([0.0086, 0.0215, 0.0776,  ..., 0.0851, 0.0180, 0.0193], device='cuda:0',
       dtype=torch.float16)
tensor([0.0309, 0.0621, 0.0967,  ..., 0.0348, 0.0096, 0.0261], device='cuda:0',
       dtype=torch.float16)
tensor([0.0229, 0.0046, 0.1166,  ..., 0.2026, 0.0204, 0.0189], device='cuda:0',
       dtype=torch.float16)
tensor([0.0216, 0.0140, 0.0116,  ..., 0.0895, 0.0983, 0.0600], device='cuda:0',
       dtype=torch.float16)
tensor([0.0149, 0.0151, 0.0130,  ..., 0.1307, 0.0109, 0.0467], device='cuda:0',
       dtype=torch.float16)
